[build]
  functions = "netlify/functions"
  publish = "out"
  environment = { NODE_VERSION = "22" }

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["resend"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
